С ветки dev
Error: Could not find or load main class com.example.hw_comand.HwComandApplication
Caused by: java.lang.ClassNotFoundException: com.example.hw_comand.HwComandApplication